//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inzPJATKSNM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Muzyka
    {
        public Muzyka()
        {
            this.Ankieta = new HashSet<Ankieta>();
        }
        [Key]
        public int Id_Muzyka { get; set; }
        public string Muzyka1 { get; set; }
    
        public virtual ICollection<Ankieta> Ankieta { get; set; }
    }
}
